name: Build Jenkins AMI Workflow

on:  
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  validate-ami:

    # specify runner
    runs-on: ubuntu-20.04

    steps:
      # checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
      
      # validate json template
    - name: Validate template
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        AMI_USERS: ${{ secrets.AMI_USERS }}
      run: packer validate ubuntu-ami.json

  build-ami:

    # specify runner
    runs-on: ubuntu-20.04

    steps:
      # checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
      
      # build ami using packer
    - name: Build AMI using template
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        AMI_USERS: ${{ secrets.AMI_USERS }}
      run: packer build ubuntu-ami.json
      